[project]
name = "phd-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.8",
    "nbconvert>=7.17.1",
    "nbformat>=5.10.4",
    "numpy>=2.5.1",
    "pytest>=9.0.2",
    "python-pptx>=1.0.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
